- name: MySQL servers
  hosts: web
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: Ensure MySQL is started and enabled
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
